JWT_SECRET = "your-256-bit-secret"

[dbConfig]
user="uhqksvuk66o0cb94"
password="Vo57RyCoCbXm3Iiloj66"
host="bpwoq9itspvyqwdlrffe-mysql.services.clever-cloud.com"
port=3306
name="bpwoq9itspvyqwdlrffe"


